CREATE TABLE LEDGER (
    LEDGER_ID       BIGSERIAL       PRIMARY KEY,
    LEDGER_DATE     DATE            NOT NULL,
    ASSET_TYPE      VARCHAR(10)     NOT NULL,
    TRANSACTION_TYPE VARCHAR(10)    NOT NULL,
    GOLD_AMOUNT     NUMERIC(10, 3),
    MONEY_AMOUNT    BIGINT,
    DESCRIPTION     VARCHAR(255),
    CREATED_BY      VARCHAR(255)
);

CREATE INDEX IDX_LEDGER_ASSET_DATE ON LEDGER (ASSET_TYPE, LEDGER_DATE);
CREATE INDEX IDX_LEDGER_DATE ON LEDGER (LEDGER_DATE);
