spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-on-validation-error: false

logging:
  level:
    com.msa.jewelry: DEBUG
    org.hibernate.SQL: DEBUG

FILE_UPLOAD_PATH2: C:\\Users\\zks14\\Desktop\\multi_module\\product-service\\src\\main\\resources\\app\\images
