CREATE TABLE PRIORITY (
    PRIORITY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRIORITY_NAME VARCHAR(255) UNIQUE,
    PRIORITY_DATE VARCHAR(255)
);
INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('일반', '7');
INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('급', '5');
INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('초급', '4');

CREATE TABLE ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_CODE VARCHAR(255),
    STORE_NAME VARCHAR(255),
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_SIZE VARCHAR(255),
    PRODUCT_LABOR_COST VARCHAR(255),
    ORDER_NOTE VARCHAR(255),
    FACTORY_NAME VARCHAR(255),
    MATERIAL_NAME VARCHAR(255),
    COLOR_NAME VARCHAR(255),
    QUANTITY INTEGER,
    ORDER_MAIN_STONE_QUANTITY INT,
    ORDER_AUXILIARY_STONE_QUANTITY INT,
    PRIORITY_ID BIGINT,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT FK_ORDERS_PRIORITY FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY(PRIORITY_ID)
);

CREATE TABLE STATUS_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    CREATE_AT VARCHAR(255),
    USER_NAME VARCHAR(255),
    ORDER_ID BIGINT,
    CONSTRAINT FK_STATUS_HISTORY_ORDERS
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
