CREATE TABLE PRIORITY (
    PRIORITY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRIORITY_NAME VARCHAR(255) UNIQUE,
    PRIORITY_DATE VARCHAR(255)
);
CREATE TABLE ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_CODE VARCHAR(255),
    STORE_NAME VARCHAR(255),
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_SIZE VARCHAR(255),
    PRODUCT_LABOR_COST VARCHAR(255),
    ORDER_NOTE VARCHAR(255),
    FACTORY_NAME VARCHAR(255),
    CLASSIFICATION_NAME VARCHAR(255),
    COLOR_NAME VARCHAR(255),
    QUANTITY INTEGER,
    ORDER_MAIN_STONE_QUANTITY INT,
    ORDER_AUXILIARY_STONE_QUANTITY INT,
    PRIORITY_ID BIGINT,
    CONSTRAINT FK_ORDERS_PRIORITY FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY(PRIORITY_ID)
);

CREATE TABLE STATUS_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STATUS_TYPE VARCHAR(50),   -- ORDER, INVENTORY, SHIPPING, RENT, FIX, CANCEL 등
    CREATE_AT DATETIME,
    USER_NAME VARCHAR(255),
    ORDER_ID BIGINT,
    CONSTRAINT FK_STATUS_HISTORY_ORDERS
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
