CREATE TABLE PRIORITY (
    PRIORITY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRIORITY_NAME VARCHAR(255) UNIQUE,
    PRIORITY_DATE INTEGER
);

INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('일반', 7);
INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('급', 5);
INSERT INTO PRIORITY (PRIORITY_NAME, PRIORITY_DATE) VALUES ('초급', 4);

CREATE TABLE ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FLOW_CODE BIGINT,
    STORE_ID BIGINT,
    STORE_NAME VARCHAR(255),
    FACTORY_ID BIGINT,
    FACTORY_NAME VARCHAR(255),
    ORDER_NOTE VARCHAR(255),
    PRIORITY_ID BIGINT,
    PRODUCT_STATUS VARCHAR(50) NOT NULL,
    ORDER_STATUS   VARCHAR(50) NOT NULL,
    ORDER_MAIN_STONE_NOTE VARCHAR(255),
    ORDER_ASSISTANCE_STONE_NOTE VARCHAR(255),
    ORDER_DATE TIMESTAMP,
    ORDER_EXPECT_DATE TIMESTAMP,
    ORDER_DELETED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_ORDERS_PRIORITY FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY(PRIORITY_ID),
    CONSTRAINT UK_ORDERS_FLOW_CODE UNIQUE (FLOW_CODE)
    );

CREATE INDEX IX_ORDERS_STATUS   ON ORDERS (PRODUCT_STATUS, ORDER_STATUS);
CREATE INDEX IX_ORDERS_PRIORITY ON ORDERS (PRIORITY_ID);
CREATE INDEX IX_ORDERS_DATE     ON ORDERS (ORDER_DATE);

CREATE TABLE ORDER_PRODUCT (
    ORDER_PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT UNIQUE,
    PRODUCT_ID BIGINT,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_SIZE VARCHAR(50),
    IS_PRODUCT_WEIGHT_SALE BOOLEAN,
    PRODUCT_WEIGHT DECIMAL(8, 2),
    STONE_WEIGHT DECIMAL(8, 2),
    PRODUCT_PURCHASE_COST INT,
    PRODUCT_LABOR_COST INT,
    PRODUCT_ADD_LABOR_COST INT,
    MATERIAL_NAME VARCHAR(100),
    CLASSIFICATION_NAME VARCHAR(100),
    COLOR_NAME VARCHAR(100),
    CONSTRAINT FK_ORDER_PRODUCT_ORDERS
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE STOCK (
    STOCK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STOCK_CODE VARCHAR(255) ,
    FLOW_CODE  BIGINT NOT NULL,
    STORE_ID BIGINT,
    STORE_NAME VARCHAR(255),
    FACTORY_ID BIGINT,
    FACTORY_NAME VARCHAR(255),
    STOCK_NOTE VARCHAR(255),
    STOCK_MAIN_STONE_NOTE VARCHAR(255),
    STOCK_ASSISTANCE_STONE_NOTE VARCHAR(255),
    MAIN_STONE_LABOR_COST   INT,
    ASSISTANCE_STONE_LABOR_COST INT,
    ADD_STONE_LABOR_COST     INT,
    PRODUCT_ID BIGINT,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_SIZE VARCHAR(50),
    IS_PRODUCT_WEIGHT_SALE BOOLEAN,
    PRODUCT_LABOR_COST INT,
    PRODUCT_ADD_LABOR_COST INT,
    PRODUCT_PURCHASE_COST INT,
    TOTAL_STONE_PURCHASE_COST INT,
    MATERIAL_NAME VARCHAR(100),
    COLOR_NAME VARCHAR(100),
    CLASSIFICATION_NAME VARCHAR(100),
    PRODUCT_WEIGHT DECIMAL(8, 2),
    STONE_WEIGHT   DECIMAL(8, 2),

    STOCK_CREATE_AT TIMESTAMP NOT NULL,
    STOCK_DELETED BOOLEAN DEFAULT FALSE,

    ORDER_ID BIGINT,
    ORDER_STATUS VARCHAR(50) NOT NULL,

    CONSTRAINT FK_STOCK_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT UK_STOCK_CODE UNIQUE (STOCK_CODE),
    CONSTRAINT UK_STOCK_FLOW_CODE UNIQUE (FLOW_CODE),
    CONSTRAINT UK_STOCK_ORDER UNIQUE (ORDER_ID)   -- 주문당 재고 1건(1:1) 보장
    );

CREATE INDEX IX_STOCK_CREATE_AT ON STOCK (STOCK_CREATE_AT);

-- ORDER_STONE 테이블
CREATE TABLE ORDER_STONE (
    ORDER_STONE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORIGIN_STONE_ID BIGINT,
    ORIGIN_STONE_NAME VARCHAR(255),
    ORIGIN_STONE_WEIGHT DECIMAL(8, 2),
    STONE_PURCHASE_COST INTEGER,
    STONE_LABOR_COST INTEGER,
    STONE_QUANTITY INTEGER,
    PRODUCT_STONE_MAIN BOOLEAN,
    INCLUDE_QUANTITY BOOLEAN,
    INCLUDE_WEIGHT BOOLEAN,
    INCLUDE_LABOR BOOLEAN,
    ORDER_ID BIGINT,
    STOCK_ID BIGINT,
    CONSTRAINT FK_ORDER_STONE_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDER_STONE_STOCK  FOREIGN KEY (STOCK_ID)  REFERENCES STOCK(STOCK_ID)
);

CREATE INDEX IX_ORDER_STONE_ORDER ON ORDER_STONE (ORDER_ID);
CREATE INDEX IX_ORDER_STONE_STOCK ON ORDER_STONE (STOCK_ID);

-- STATUS_HISTORY 테이블
CREATE TABLE STATUS_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FLOW_CODE   BIGINT NOT NULL,
    SOURCE_TYPE VARCHAR(32) ,     -- ORDER / FIX / NORMAL
    PHASE       VARCHAR(32) ,     -- ORDER / WAITING / ORDER_FAIL / STOCK / STOCK_FAIL / FIX / NORMAL / RENTAL / RETURN / SALE / DELETE
    KIND        VARCHAR(32) ,     -- CREATE / UPDATE / DELETE / RESTORE
    FROM_VALUE  VARCHAR(255),
    TO_VALUE    VARCHAR(255),
    CREATED_AT  TIMESTAMP,
    USER_NAME   VARCHAR(255)
    );

CREATE INDEX idx_hist_flowcode_created ON STATUS_HISTORY (FLOW_CODE, CREATED_AT);