ALTER TABLE OUT_BOX_EVENT ADD COLUMN IF NOT EXISTS RETRY_COUNT INTEGER DEFAULT 0;
ALTER TABLE OUT_BOX_EVENT ADD COLUMN IF NOT EXISTS LAST_ERROR_MESSAGE VARCHAR(500);
ALTER TABLE OUT_BOX_EVENT ADD COLUMN IF NOT EXISTS NEXT_RETRY_AT TIMESTAMPTZ;
ALTER TABLE OUT_BOX_EVENT ADD COLUMN IF NOT EXISTS EVENT_TYPE VARCHAR(50);

ALTER TABLE OUT_BOX_EVENT ALTER COLUMN PAYLOAD TYPE TEXT;

-- 3. 필수 제약 조건 반영
ALTER TABLE OUT_BOX_EVENT ALTER COLUMN TOPIC SET NOT NULL;
ALTER TABLE OUT_BOX_EVENT ALTER COLUMN MESSAGE_KEY SET NOT NULL;
ALTER TABLE OUT_BOX_EVENT ALTER COLUMN PAYLOAD SET NOT NULL;
ALTER TABLE OUT_BOX_EVENT ALTER COLUMN EVENT_STATUS SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_status_created ON OUT_BOX_EVENT (EVENT_STATUS, create_date);
CREATE INDEX IF NOT EXISTS idx_topic_status ON OUT_BOX_EVENT (TOPIC, EVENT_STATUS);