-- 재고 조사 기능을 위한 컬럼 추가
ALTER TABLE STOCK ADD COLUMN STOCK_CHECKED BOOLEAN DEFAULT FALSE;
ALTER TABLE STOCK ADD COLUMN STOCK_CHECKED_AT TIMESTAMP;

-- 인덱스 추가 (재고 조사 조회 성능 향상)
CREATE INDEX idx_stock_checked ON STOCK(STOCK_CHECKED);
CREATE INDEX idx_stock_checked_at ON STOCK(STOCK_CHECKED_AT);
