ALTER TABLE GOLD ADD COLUMN IF NOT EXISTS CREATE_DATE TIMESTAMP;
ALTER TABLE GOLD ADD COLUMN IF NOT EXISTS LAST_MODIFIED_DATE TIMESTAMP;

UPDATE GOLD
SET CREATE_DATE = CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHERE CREATE_DATE IS NULL;