-- 공장별 스톤 조각료 테이블 제거
DROP INDEX IF EXISTS IDX_FACTORY_STONE_PRICE_EFFECTIVE;
DROP INDEX IF EXISTS IDX_FACTORY_STONE_PRICE_STONE;
DROP INDEX IF EXISTS IDX_FACTORY_STONE_PRICE_FACTORY;
DROP TABLE IF EXISTS FACTORY_STONE_PRICE;
