ALTER TABLE PRODUCT_STONE ADD COLUMN IF NOT EXISTS INCLUDE_QUANTITY BOOLEAN DEFAULT true;
ALTER TABLE PRODUCT_STONE ADD COLUMN IF NOT EXISTS INCLUDE_PRICE BOOLEAN DEFAULT true;

UPDATE PRODUCT_STONE SET INCLUDE_QUANTITY = true WHERE INCLUDE_QUANTITY IS NULL;
UPDATE PRODUCT_STONE SET INCLUDE_PRICE = true WHERE INCLUDE_PRICE IS NULL;
