CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(10) NOT NULL,
    TENANT_ID VARCHAR(10) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATE_DATE VARCHAR(19) NOT NULL,
    LAST_MODIFIED_DATE VARCHAR(19) NOT NULL
);