CREATE TABLE CLASSIFICATION (
    CLASSIFICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASSIFICATION_NAME VARCHAR(255) UNIQUE,
    CLASSIFICATION_NOTE VARCHAR(255)
);

CREATE TABLE MATERIAL (
    MATERIAL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATERIAL_NAME VARCHAR(255) UNIQUE,
    MATERIAL_GOLD_PURITY_PERCENT DECIMAL(5, 2)
);

CREATE TABLE SET_TYPE (
    SET_TYPE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SET_TYPE_NAME VARCHAR(255) UNIQUE,
    SET_TYPE_NOTE VARCHAR(255)
);

CREATE TABLE STONE_SHAPE (
    STONE_SHAPE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STONE_SHAPE_NAME VARCHAR(255),
    STONE_SHAPE_NOTE VARCHAR(255)
);

CREATE TABLE STONE_TYPE (
    STONE_TYPE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STONE_TYPE_NAME VARCHAR(255),
    STONE_TYPE_NOTE VARCHAR(255)
);

CREATE TABLE STONE (
    STONE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STONE_NAME VARCHAR(255) UNIQUE,
    STONE_NOTE VARCHAR(255),
    STONE_WEIGHT DECIMAL(5, 2),
    STONE_PURCHASE_PRICE VARCHAR(255)
);

CREATE TABLE STONE_WORK_GRADE_POLICY (
    STONE_WORK_GRADE_POLICY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STONE_ID BIGINT NOT NULL,
    GRADE VARCHAR(255) NOT NULL,
    LABOR_COST INTEGER,
    CONSTRAINT FK_STONE_WORK_GRADE_POLICY__STONE FOREIGN KEY (STONE_ID) REFERENCES STONE(STONE_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACTORY_ID BIGINT,
    PRODUCT_FACTORY_NAME VARCHAR(255),
    PRODUCT_NAME VARCHAR(255) NOT NULL UNIQUE,
    SET_TYPE_ID BIGINT,
    CLASSIFICATION_ID BIGINT,
    MATERIAL_ID BIGINT,
    STANDARD_WEIGHT DECIMAL(19, 2),
    PRODUCT_NOTE VARCHAR(255),
    CONSTRAINT FK_PRODUCT_SET_TYPE FOREIGN KEY (SET_TYPE_ID) REFERENCES SET_TYPE(SET_TYPE_ID),
    CONSTRAINT FK_PRODUCT_CLASSIFICATION FOREIGN KEY (CLASSIFICATION_ID) REFERENCES CLASSIFICATION(CLASSIFICATION_ID),
    CONSTRAINT FK_PRODUCT_MATERIAL FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL(MATERIAL_ID)
);

CREATE TABLE PRODUCT_IMAGE (
    IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_URL VARCHAR(255) NOT NULL,
    IMAGE_NAME VARCHAR(255) NOT NULL,
    IMAGE_ORIGIN_NAME VARCHAR(255) NOT NULL,
    PRODUCT_ID BIGINT,
    CONSTRAINT FK_PRODUCT_IMAGE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PRODUCT_STONE (
    PRODUCT_STONE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    STONE_ID BIGINT NOT NULL,
    INCLUDE_QUANTITY BOOLEAN,
    STONE_QUANTITY INTEGER,
    CONSTRAINT FK_PRODUCT_STONE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_STONE_STONE FOREIGN KEY (STONE_ID) REFERENCES STONE(STONE_ID)
);

CREATE TABLE PRODUCT_WORK_GRADE_POLICY (
    PRODUCT_WORK_GRADE_POLICY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    GRADE VARCHAR(255) NOT NULL,
    LABOR_COST INTEGER,
    PRODUCT_POLICY_NOTE VARCHAR(255),
    CONSTRAINT FK_WORK_POLICY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);