-- ADDRESS TABLE
CREATE TABLE IF NOT EXISTS ADDRESS (
    ADDRESS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS_ZIP_CODE VARCHAR(10),
    ADDRESS_BASIC VARCHAR(255),
    ADDRESS_ADD VARCHAR(255),
    DELETED BOOLEAN DEFAULT FALSE
);

-- GOLD_HARRY TABLE
CREATE TABLE IF NOT EXISTS GOLD_HARRY (
    GOLD_HARRY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOLD_HARRY_LOSS DECIMAL(19,2) NOT NULL,
    DEFAULT_OPTION BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED BOOLEAN DEFAULT FALSE
);

INSERT INTO GOLD_HARRY (GOLD_HARRY_LOSS, DEFAULT_OPTION) VALUES (1.10, TRUE);

-- COMMON_OPTION TABLE
CREATE TABLE IF NOT EXISTS COMMON_OPTION (
    COMMON_OPTION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    OPTION_TRADE_TYPE VARCHAR(30),
    OPTION_LEVEL VARCHAR(30),
    DELETED BOOLEAN DEFAULT FALSE,
    GOLD_HARRY_ID BIGINT NOT NULL,
    GOLD_HARRY_LOSS VARCHAR(5),
    CONSTRAINT FK_COMMON_OPTION_GOLD FOREIGN KEY (GOLD_HARRY_ID) REFERENCES GOLD_HARRY(GOLD_HARRY_ID) ON DELETE RESTRICT
);

-- ADDITIONAL_OPTION TABLE
CREATE TABLE IF NOT EXISTS ADDITIONAL_OPTION (
    OPTION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    OPTION_APPLY_PAST_SALES BOOLEAN NOT NULL,
    OPTION_MATERIAL_ID VARCHAR(255),
    OPTION_MATERIAL_NAME VARCHAR(255),
    DELETED BOOLEAN DEFAULT FALSE
);

-- STORE TABLE
CREATE TABLE IF NOT EXISTS STORE (
    STORE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STORE_NAME VARCHAR(30) NOT NULL UNIQUE,
    STORE_OWNER_NAME VARCHAR(30) NOT NULL,
    STORE_PHONE_NUMBER VARCHAR(13),
    STORE_CONTACT_NUMBER_1 VARCHAR(13),
    STORE_CONTACT_NUMBER_2 VARCHAR(13),
    STORE_FAX_NUMBER VARCHAR(16),
    STORE_NOTE VARCHAR(255),
    STORE_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    STORE_DELETED BOOLEAN NOT NULL DEFAULT FALSE,

    CREATE_DATE VARCHAR(19) NOT NULL,
    LAST_MODIFIED_DATE VARCHAR(19) NOT NULL,

    CREATED_BY VARCHAR(255),
    LAST_MODIFIED_BY VARCHAR(255),

    ADDRESS_ID BIGINT,
    COMMON_OPTION_ID BIGINT,
    OPTION_ID BIGINT,

    CONSTRAINT FK_STORE_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORE_COMMON_OPTION FOREIGN KEY (COMMON_OPTION_ID) REFERENCES COMMON_OPTION(COMMON_OPTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORE_ADDITIONAL_OPTION FOREIGN KEY (OPTION_ID) REFERENCES ADDITIONAL_OPTION(OPTION_ID) ON DELETE CASCADE
);

INSERT INTO STORE (STORE_NAME, STORE_OWNER_NAME, STORE_DEFAULT, STORE_DELETED, CREATE_DATE, LAST_MODIFIED_DATE)
SELECT '매장재고', '매장재고', TRUE, FALSE,
       FORMATDATETIME(CURRENT_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss'),
       FORMATDATETIME(CURRENT_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss')
WHERE NOT EXISTS (SELECT 1 FROM STORE WHERE STORE_NAME = '매장재고');

INSERT INTO COMMON_OPTION (OPTION_TRADE_TYPE, OPTION_LEVEL, DELETED, GOLD_HARRY_ID, GOLD_HARRY_LOSS)
SELECT 'WEIGHT', 'ONE', FALSE, gh.GOLD_HARRY_ID, CAST(gh.GOLD_HARRY_LOSS AS VARCHAR(5))
FROM GOLD_HARRY gh
WHERE gh.DEFAULT_OPTION = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM COMMON_OPTION co
    WHERE co.GOLD_HARRY_ID = gh.GOLD_HARRY_ID
      AND co.OPTION_TRADE_TYPE = 'WEIGHT'
      AND co.OPTION_LEVEL = 'ONE'
      AND co.DELETED = FALSE
);

UPDATE STORE s
SET s.COMMON_OPTION_ID = (
    SELECT co.COMMON_OPTION_ID
    FROM COMMON_OPTION co
    WHERE co.OPTION_TRADE_TYPE = 'WEIGHT'
      AND co.OPTION_LEVEL = 'ONE'
      AND co.DELETED = FALSE
    ORDER BY co.COMMON_OPTION_ID
        FETCH FIRST 1 ROW ONLY
)
WHERE (s.STORE_NAME = '매장재고' OR s.STORE_DEFAULT = TRUE)
  AND s.COMMON_OPTION_ID IS NULL;

-- FACTORY TABLE
CREATE TABLE IF NOT EXISTS FACTORY (
    FACTORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FACTORY_NAME VARCHAR(30) NOT NULL UNIQUE,
    FACTORY_OWNER_NAME VARCHAR(30) NOT NULL,
    FACTORY_PHONE_NUMBER VARCHAR(13),
    FACTORY_CONTACT_NUMBER_1 VARCHAR(13),
    FACTORY_CONTACT_NUMBER_2 VARCHAR(13),
    FACTORY_FAX_NUMBER VARCHAR(16),
    FACTORY_NOTE VARCHAR(255),
    FACTORY_DELETED BOOLEAN NOT NULL DEFAULT FALSE,

    CREATE_DATE VARCHAR(19) NOT NULL,
    LAST_MODIFIED_DATE VARCHAR(19) NOT NULL,

    CREATED_BY VARCHAR(255),
    LAST_MODIFIED_BY VARCHAR(255),

    ADDRESS_ID BIGINT,
    COMMON_OPTION_ID BIGINT,

    CONSTRAINT FK_FACTORY_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FACTORY_COMMON_OPTION FOREIGN KEY (COMMON_OPTION_ID) REFERENCES COMMON_OPTION(COMMON_OPTION_ID) ON DELETE CASCADE
);