CREATE TABLE IF NOT EXISTS SALE_LOG (
    ACCOUNT_SALE_CODE BIGINT PRIMARY KEY,
    PREVIOUS_GOLD_BALANCE DECIMAL(10, 3) DEFAULT 0.000,
    PREVIOUS_MONEY_BALANCE BIGINT DEFAULT 0,
    SALE_DATE TIMESTAMPTZ
);

INSERT INTO SALE_LOG (ACCOUNT_SALE_CODE, PREVIOUS_GOLD_BALANCE, PREVIOUS_MONEY_BALANCE, SALE_DATE)
SELECT
    th.ACCOUNT_SALE_CODE,
    0.000,
    0,
    MIN(th.TRANSACTION_DATE)
FROM TRANSACTION_HISTORY th
WHERE th.ACCOUNT_SALE_CODE IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM SALE_LOG sl WHERE sl.ACCOUNT_SALE_CODE = th.ACCOUNT_SALE_CODE
)
GROUP BY th.ACCOUNT_SALE_CODE;