DROP TABLE IF EXISTS SALE_LOG;


CREATE TABLE SALE_LOG (
    SALE_LOG_ID BIGSERIAL PRIMARY KEY,

    ACCOUNT_SALE_CODE BIGINT NOT NULL,

    STORE_ID BIGINT,
    FACTORY_ID BIGINT,
    OWNER_TYPE VARCHAR(20) NOT NULL,

    PREVIOUS_GOLD_BALANCE DECIMAL(10, 3) DEFAULT 0.000,
    PREVIOUS_MONEY_BALANCE BIGINT DEFAULT 0,

    AFTER_GOLD_BALANCE DECIMAL(10, 3) DEFAULT 0.000,
    AFTER_MONEY_BALANCE BIGINT DEFAULT 0,

    SALE_DATE TIMESTAMPTZ,

    CONSTRAINT idx_sale_log_code UNIQUE (ACCOUNT_SALE_CODE, STORE_ID, FACTORY_ID, OWNER_TYPE)
);

CREATE INDEX idx_sale_log_store ON SALE_LOG(STORE_ID);
CREATE INDEX idx_sale_log_factory ON SALE_LOG(FACTORY_ID);

INSERT INTO SALE_LOG (
    ACCOUNT_SALE_CODE,
    STORE_ID,
    OWNER_TYPE,
    PREVIOUS_GOLD_BALANCE,
    PREVIOUS_MONEY_BALANCE,
    AFTER_GOLD_BALANCE,
    AFTER_MONEY_BALANCE,
    SALE_DATE
)
SELECT
    th.ACCOUNT_SALE_CODE,
    th.STORE_ID,
    'STORE',
    0.000,
    0,
    0.000,
    0,
    MIN(th.TRANSACTION_DATE)
FROM TRANSACTION_HISTORY th
WHERE th.ACCOUNT_SALE_CODE IS NOT NULL
  AND th.STORE_ID IS NOT NULL
GROUP BY th.ACCOUNT_SALE_CODE, th.STORE_ID;

INSERT INTO SALE_LOG (
    ACCOUNT_SALE_CODE,
    FACTORY_ID,
    OWNER_TYPE,
    PREVIOUS_GOLD_BALANCE,
    PREVIOUS_MONEY_BALANCE,
    AFTER_GOLD_BALANCE,
    AFTER_MONEY_BALANCE,
    SALE_DATE
)
SELECT
    th.ACCOUNT_SALE_CODE,
    th.FACTORY_ID,
    'FACTORY', -- Owner Type 지정
    0.000,
    0,
    0.000,
    0,
    MIN(th.TRANSACTION_DATE)
FROM TRANSACTION_HISTORY th
WHERE th.ACCOUNT_SALE_CODE IS NOT NULL
  AND th.FACTORY_ID IS NOT NULL -- 공장 ID가 있는 데이터만
GROUP BY th.ACCOUNT_SALE_CODE, th.FACTORY_ID;