-- ====================================================================
-- jewelry_emp Monolith Unified Schema (V1 baseline)
--
-- Target  : PostgreSQL (cloud DB)
-- Profile : per-tenant schema (SchemaMultiTenantConnectionProvider 가
--           각 tenant 스키마를 검색 경로로 설정한 뒤 Flyway 가 본 SQL 을 적용)
-- Source  : multi_module 4 개 모듈(account / product / order / user) 의
--           모든 @Entity / @Embeddable 정의를 정확히 따른 통합 베이스라인.
--
-- 정규화 노트
--   - ProductSnapshot @Embeddable 은 stock 테이블에 그대로 인라인된다
--     (현재 엔티티 그대로 유지). 컬럼 의미를 중복(=denorm)/freeze(=time-frozen)
--     으로 구분해 주석에 표시했으니, 후속 정리에서 denorm 컬럼만 제거하기 쉽게 했다.
--   - orders / stock / sale 의 store_*/factory_*/account_* 컬럼 중
--     *_harry, *_grade, *_gold_price 는 거래 시점 freeze 값이라 유지.
--     *_name 은 denorm(향후 FK join 으로 대체 가능).
--   - Hibernate 의 CamelCaseToUnderscoresNamingStrategy 와
--     PostgreSQL 의 unquoted-identifier-folding 규칙에 맞추어 모든 식별자는 lower_snake_case.
-- ====================================================================

-- ====================================================================
-- 0. 안전 재실행을 위한 cleanup (기존 placeholder 잔재가 있을 때만 의미 있음)
--    Flyway 는 V1 을 한 번만 실행하지만, 새 스키마에 다른 잔재가 있을 수 있어
--    DROP 을 명시적으로 두지 않는다 (이미 적용된 경우 V2 로 변경분 이행).
-- ====================================================================

-- ====================================================================
-- 1. 공통 lookup / master 테이블 (FK 의존 없음)
-- ====================================================================

CREATE TABLE address (
    address_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_zip_code  VARCHAR(255),
    address_basic     VARCHAR(255),
    address_add       VARCHAR(255)
);

CREATE TABLE gold_harry (
    gold_harry_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gold_harry_loss   NUMERIC(10, 2)  NOT NULL,
    default_option    BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE TABLE common_option (
    common_option_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_trade_type    VARCHAR(30),
    option_level         VARCHAR(30),
    gold_harry_id        BIGINT       NOT NULL,
    gold_harry_loss      VARCHAR(255),
    CONSTRAINT fk_common_option_gold_harry
        FOREIGN KEY (gold_harry_id) REFERENCES gold_harry (gold_harry_id)
);

CREATE TABLE additional_option (
    option_id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_apply_past_sales  BOOLEAN      NOT NULL DEFAULT FALSE,
    option_material_id       VARCHAR(255), -- product 매핑용 식별자(legacy)
    option_material_name     VARCHAR(255)  -- 단건 조회 편의용 denorm
);

CREATE TABLE classification (
    classification_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name   VARCHAR(255) UNIQUE,
    classification_note   VARCHAR(255),
    default_id            BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE color (
    color_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_name   VARCHAR(255) UNIQUE,
    color_note   VARCHAR(255),
    default_id   BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE material (
    material_id                    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_name                  VARCHAR(255)    UNIQUE,
    material_gold_purity_percent   NUMERIC(5, 2),
    default_id                     BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE TABLE set_type (
    set_type_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_type_name   VARCHAR(255) UNIQUE,
    set_type_note   VARCHAR(255),
    default_id      BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE stone_shape (
    stone_shape_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stone_shape_name   VARCHAR(255) UNIQUE,
    stone_shape_note   VARCHAR(255)
);

CREATE TABLE stone_type (
    stone_type_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stone_type_name   VARCHAR(255) UNIQUE,
    stone_type_note   VARCHAR(255)
);

CREATE TABLE assistance_stone (
    assistance_stone_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistance_stone_name      VARCHAR(255),
    assistance_stone_note      VARCHAR(255),
    assistance_stone_deleted   BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE priority (
    priority_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority_name   VARCHAR(255) UNIQUE,
    priority_date   INTEGER
);

-- ====================================================================
-- 2. account 모듈
-- ====================================================================

-- Audit: BaseEntity (create_date, last_modified_date, created_by, last_modified_by)
CREATE TABLE expense_bank_type (
    expense_bank_type_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_type_name          VARCHAR(100)  NOT NULL,
    bank_type_note          VARCHAR(255),
    deleted                 BOOLEAN       NOT NULL DEFAULT FALSE,
    create_date             TIMESTAMP,
    last_modified_date      TIMESTAMP,
    created_by              VARCHAR(255),
    last_modified_by        VARCHAR(255)
);

CREATE TABLE expense_expense_account (
    expense_expense_account_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_account_name        VARCHAR(100)  NOT NULL,
    expense_account_note        VARCHAR(255),
    deleted                     BOOLEAN       NOT NULL DEFAULT FALSE,
    create_date                 TIMESTAMP,
    last_modified_date          TIMESTAMP,
    created_by                  VARCHAR(255),
    last_modified_by            VARCHAR(255)
);

CREATE TABLE expense_income_account (
    expense_income_account_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_account_name        VARCHAR(100)  NOT NULL,
    income_account_note        VARCHAR(255),
    deleted                    BOOLEAN       NOT NULL DEFAULT FALSE,
    create_date                TIMESTAMP,
    last_modified_date         TIMESTAMP,
    created_by                 VARCHAR(255),
    last_modified_by           VARCHAR(255)
);

CREATE TABLE expense_record (
    expense_record_id           BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_date                 TIMESTAMP       NOT NULL,
    expense_type                VARCHAR(20)     NOT NULL,
    expense_bank_type_id        BIGINT,
    expense_income_account_id   BIGINT,
    expense_expense_account_id  BIGINT,
    counterparty                VARCHAR(100),
    description                 VARCHAR(500),
    material                    VARCHAR(50),
    weight                      NUMERIC(10, 3),
    quantity                    INTEGER         DEFAULT 1,
    unit_price                  BIGINT          DEFAULT 0,
    supply_amount               BIGINT          DEFAULT 0,
    tax_amount                  BIGINT          DEFAULT 0,
    deleted                     BOOLEAN         NOT NULL DEFAULT FALSE,
    create_date                 TIMESTAMP,
    last_modified_date          TIMESTAMP,
    created_by                  VARCHAR(255),
    last_modified_by            VARCHAR(255),
    CONSTRAINT fk_expense_record_bank_type
        FOREIGN KEY (expense_bank_type_id) REFERENCES expense_bank_type (expense_bank_type_id),
    CONSTRAINT fk_expense_record_income_account
        FOREIGN KEY (expense_income_account_id) REFERENCES expense_income_account (expense_income_account_id),
    CONSTRAINT fk_expense_record_expense_account
        FOREIGN KEY (expense_expense_account_id) REFERENCES expense_expense_account (expense_expense_account_id)
);

CREATE TABLE factory (
    factory_id                BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_name              VARCHAR(30)     NOT NULL UNIQUE,
    factory_owner_name        VARCHAR(30),
    factory_phone_number      VARCHAR(13),
    factory_contact_number_1  VARCHAR(13),
    factory_contact_number_2  VARCHAR(13),
    factory_fax_number        VARCHAR(16),
    factory_note              VARCHAR(255),
    factory_deleted           BOOLEAN         NOT NULL DEFAULT FALSE,
    current_gold_balance      NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    current_money_balance     BIGINT          NOT NULL DEFAULT 0,
    address_id                BIGINT,
    common_option_id          BIGINT,
    create_date               TIMESTAMP,
    last_modified_date        TIMESTAMP,
    created_by                VARCHAR(255),
    last_modified_by          VARCHAR(255),
    CONSTRAINT fk_factory_address
        FOREIGN KEY (address_id) REFERENCES address (address_id),
    CONSTRAINT fk_factory_common_option
        FOREIGN KEY (common_option_id) REFERENCES common_option (common_option_id)
);

CREATE TABLE store (
    store_id                BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name              VARCHAR(30)     NOT NULL UNIQUE,
    store_owner_name        VARCHAR(30),
    store_phone_number      VARCHAR(13),
    store_contact_number_1  VARCHAR(13),
    store_contact_number_2  VARCHAR(13),
    store_fax_number        VARCHAR(16),
    store_note              VARCHAR(255),
    store_default           BOOLEAN         NOT NULL DEFAULT FALSE,
    store_deleted           BOOLEAN         NOT NULL DEFAULT FALSE,
    current_gold_balance    NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    current_money_balance   BIGINT          NOT NULL DEFAULT 0,
    address_id              BIGINT,
    common_option_id        BIGINT,
    option_id               BIGINT,
    create_date             TIMESTAMP,
    last_modified_date      TIMESTAMP,
    created_by              VARCHAR(255),
    last_modified_by        VARCHAR(255),
    CONSTRAINT fk_store_address
        FOREIGN KEY (address_id) REFERENCES address (address_id),
    CONSTRAINT fk_store_common_option
        FOREIGN KEY (common_option_id) REFERENCES common_option (common_option_id),
    CONSTRAINT fk_store_additional_option
        FOREIGN KEY (option_id) REFERENCES additional_option (option_id)
);

CREATE TABLE schedule (
    schedule_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(100)    NOT NULL,
    content              VARCHAR(500),
    start_at             TIMESTAMP       NOT NULL,
    end_at               TIMESTAMP       NOT NULL,
    all_day              BOOLEAN         NOT NULL DEFAULT FALSE,
    repeat_type          VARCHAR(20)     NOT NULL DEFAULT 'NONE',
    color                VARCHAR(20),
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP,
    created_by           VARCHAR(255),
    last_modified_by     VARCHAR(255)
);

-- 장부 (audit 미상속 - created_by 만 별도 컬럼)
CREATE TABLE ledger (
    ledger_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_date        DATE            NOT NULL,
    asset_type         VARCHAR(10)     NOT NULL,
    transaction_type   VARCHAR(10)     NOT NULL,
    gold_amount        NUMERIC(10, 3),
    money_amount       BIGINT,
    description        VARCHAR(255),
    created_by         VARCHAR(255)
);

-- 거래내역 (audit 미상속)
CREATE TABLE transaction_history (
    transaction_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date            TIMESTAMP       NOT NULL,
    transaction_type            VARCHAR(20),                       -- enum SaleStatus
    material                    VARCHAR(50),
    gold_amount                 NUMERIC(10, 3),
    money_amount                BIGINT,
    transaction_deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    event_id                    VARCHAR(100)    NOT NULL UNIQUE,    -- 멱등성 + 판매 연결키
    account_sale_code           BIGINT,                             -- 판매 주문장 id (TSID)
    store_id                    BIGINT,
    factory_id                  BIGINT,
    transaction_history_note    VARCHAR(255),
    CONSTRAINT fk_transaction_history_store
        FOREIGN KEY (store_id) REFERENCES store (store_id),
    CONSTRAINT fk_transaction_history_factory
        FOREIGN KEY (factory_id) REFERENCES factory (factory_id)
);

-- 판매 로그 (audit 미상속)
CREATE TABLE sale_log (
    sale_log_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_sale_code        BIGINT,
    previous_gold_balance    NUMERIC(10, 3)  DEFAULT 0,
    previous_money_balance   BIGINT          DEFAULT 0,
    after_gold_balance       NUMERIC(10, 3)  DEFAULT 0,
    after_money_balance      BIGINT          DEFAULT 0,
    sale_date                TIMESTAMP,
    store_id                 BIGINT,
    factory_id               BIGINT,
    owner_type               VARCHAR(50),
    CONSTRAINT fk_sale_log_store
        FOREIGN KEY (store_id) REFERENCES store (store_id),
    CONSTRAINT fk_sale_log_factory
        FOREIGN KEY (factory_id) REFERENCES factory (factory_id)
);

-- ====================================================================
-- 3. product 모듈
-- ====================================================================

-- 금시세 (audit: BaseTimeEntity)
CREATE TABLE gold (
    gold_id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gold_price           INTEGER,
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP
);

-- 상품 (audit: BaseEntity, soft-delete via product_deleted)
CREATE TABLE product (
    product_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_id              BIGINT,                                -- 제조사 식별자(FK 미설정 - 모듈 경계 호환)
    factory_name            VARCHAR(255),                          -- denorm. 추후 FK 조회로 대체 가능
    product_factory_name    VARCHAR(255),                          -- 제조사가 부여한 모델명
    product_name            VARCHAR(255)    NOT NULL UNIQUE,
    set_type_id             BIGINT,
    classification_id       BIGINT,
    material_id             BIGINT,
    standard_weight         NUMERIC(10, 3),
    product_note            VARCHAR(255),
    product_related_number  VARCHAR(255),
    product_deleted         BOOLEAN         DEFAULT FALSE,
    create_date             TIMESTAMP,
    last_modified_date      TIMESTAMP,
    created_by              VARCHAR(255),
    last_modified_by        VARCHAR(255),
    CONSTRAINT fk_product_set_type
        FOREIGN KEY (set_type_id) REFERENCES set_type (set_type_id),
    CONSTRAINT fk_product_classification
        FOREIGN KEY (classification_id) REFERENCES classification (classification_id),
    CONSTRAINT fk_product_material
        FOREIGN KEY (material_id) REFERENCES material (material_id)
);

-- 상품 이미지 (audit: BaseTimeEntity)
CREATE TABLE product_image (
    image_id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url             VARCHAR(255) NOT NULL,
    image_name            VARCHAR(255) NOT NULL,
    image_origin_name     VARCHAR(255) NOT NULL,
    image_main            BOOLEAN      NOT NULL DEFAULT FALSE,
    product_id            BIGINT,
    create_date           TIMESTAMP,
    last_modified_date    TIMESTAMP,
    CONSTRAINT fk_product_image_product
        FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE
);

-- 상품 작업등급 정책 그룹 (audit 미상속)
CREATE TABLE product_work_grade_policy_group (
    product_work_grade_policy_group_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_purchase_price                    INTEGER      DEFAULT 0,
    product_id                                BIGINT,
    color_id                                  BIGINT,
    product_work_grade_policy_group_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    product_note                              VARCHAR(255),
    CONSTRAINT fk_pwgpg_product
        FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE,
    CONSTRAINT fk_pwgpg_color
        FOREIGN KEY (color_id) REFERENCES color (color_id)
);

CREATE TABLE product_work_grade_policy (
    product_work_grade_policy_id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade                                   VARCHAR(20)  NOT NULL,        -- enum WorkGrade
    labor_cost                              INTEGER      DEFAULT 0,
    product_work_grade_policy_group_id      BIGINT,
    CONSTRAINT fk_pwgp_group
        FOREIGN KEY (product_work_grade_policy_group_id)
        REFERENCES product_work_grade_policy_group (product_work_grade_policy_group_id) ON DELETE CASCADE
);

-- 스톤 (audit 미상속)
CREATE TABLE stone (
    stone_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stone_name            VARCHAR(255)    UNIQUE,
    stone_note            VARCHAR(255),
    stone_weight          NUMERIC(5, 2),
    stone_purchase_price  INTEGER
);

CREATE TABLE stone_work_grade_policy (
    stone_work_grade_policy_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stone_id                     BIGINT       NOT NULL,
    grade                        VARCHAR(20)  NOT NULL,                  -- enum WorkGrade
    labor_cost                   INTEGER,
    CONSTRAINT fk_swgp_stone
        FOREIGN KEY (stone_id) REFERENCES stone (stone_id) ON DELETE CASCADE
);

-- 상품-스톤 매핑 (audit 미상속)
CREATE TABLE product_stone (
    product_stone_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id           BIGINT       NOT NULL,
    stone_id             BIGINT       NOT NULL,
    main_stone           BOOLEAN,
    include_stone        BOOLEAN,
    include_quantity     BOOLEAN,
    include_price        BOOLEAN,
    stone_quantity       INTEGER,
    product_stone_note   VARCHAR(255),
    CONSTRAINT fk_product_stone_product
        FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE,
    CONSTRAINT fk_product_stone_stone
        FOREIGN KEY (stone_id) REFERENCES stone (stone_id)
);

-- ====================================================================
-- 4. order 모듈
-- ====================================================================

-- 주문 (2026-05 P4: BaseEntity 상속, denorm 컬럼 제거)
CREATE TABLE orders (
    order_id          BIGINT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_code         BIGINT             NOT NULL,                        -- TSID, 주문/재고/판매 공통 추적키
    store_id          BIGINT,                                              -- account.store FK (이름은 storeFinder 조회)
    store_grade       VARCHAR(255),                                        -- freeze (계약 시점 등급)
    store_harry       NUMERIC(10, 2),                                      -- freeze (계약 시점 환율)
    factory_id        BIGINT,                                              -- account.factory FK (이름은 factoryFinder 조회)
    factory_harry     NUMERIC(10, 2),                                      -- freeze
    order_note        TEXT,
    -- 도메인 시각 컬럼 (사용자 입력 주문 접수일·출고일)
    create_at         TIMESTAMP,
    shipping_at       TIMESTAMP,
    order_deleted     BOOLEAN            NOT NULL DEFAULT FALSE,
    priority_id       BIGINT,
    product_status    VARCHAR(30)        NOT NULL,                         -- enum ProductStatus
    order_status      VARCHAR(30)        NOT NULL,                         -- enum OrderStatus
    -- BaseEntity 상속 audit (Orders.createAt 도메인 컬럼과 별개 의미)
    create_date       TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by        VARCHAR(255),
    last_modified_by  VARCHAR(255),
    CONSTRAINT fk_orders_store
        FOREIGN KEY (store_id) REFERENCES store (store_id),
    CONSTRAINT fk_orders_factory
        FOREIGN KEY (factory_id) REFERENCES factory (factory_id),
    CONSTRAINT fk_orders_priority
        FOREIGN KEY (priority_id) REFERENCES priority (priority_id)
);

CREATE INDEX idx_orders_flow_code     ON orders (flow_code);
CREATE INDEX idx_orders_store         ON orders (store_id);
CREATE INDEX idx_orders_factory       ON orders (factory_id);
CREATE INDEX idx_orders_status        ON orders (order_status);
CREATE INDEX idx_orders_create_at     ON orders (create_at);

-- 주문 상품 (Orders 와 1:1, FK 측 보유. audit 미상속)
-- 주의: PRODUCT_NAME/MATERIAL_*/COLOR_*/CLASSIFICATION_*/SET_TYPE_*/ASSISTANT_STONE_NAME 는
-- product 테이블 lookup 으로 대체 가능한 denorm 컬럼이지만, 현재 엔티티가 그대로 사용 중이라 유지.
-- LABOR_COST/ADD_LABOR_COST/PURCHASE_COST 는 주문 시점 freeze 라 정상 보유.
CREATE TABLE order_product (
    order_product_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                      BIGINT          UNIQUE,                           -- 1:1
    product_id                    BIGINT,                                            -- product FK (수동 보관)
    product_name                  VARCHAR(255),                                      -- denorm
    product_factory_name          VARCHAR(255),                                      -- denorm
    product_size                  VARCHAR(255),                                      -- 주문 인스턴스 고유 값
    is_product_weight_sale        BOOLEAN         DEFAULT FALSE,
    gold_weight                   NUMERIC(10, 3),                                    -- 인스턴스 실측치
    stone_weight                  NUMERIC(10, 3),                                    -- 인스턴스 실측치
    order_main_stone_note         TEXT,
    order_assistance_stone_note   TEXT,
    product_purchase_cost         INTEGER,                                           -- freeze
    product_labor_cost            INTEGER,                                           -- freeze (등급별)
    product_add_labor_cost        INTEGER,                                           -- freeze
    material_id                   BIGINT,                                            -- denorm (lookup)
    material_name                 VARCHAR(255),                                      -- denorm
    classification_id             BIGINT,                                            -- denorm
    classification_name           VARCHAR(255),                                      -- denorm
    color_id                      BIGINT,                                            -- denorm
    color_name                    VARCHAR(255),                                      -- denorm
    set_type_id                   BIGINT,                                            -- denorm
    set_type_name                 VARCHAR(255),                                      -- denorm
    assistant_stone               BOOLEAN         NOT NULL DEFAULT FALSE,            -- 보조석 사용 여부
    assistant_stone_id            BIGINT,                                            -- assistance_stone FK
    assistant_stone_name          VARCHAR(255),                                      -- denorm
    assistant_stone_create_at     TIMESTAMP,
    CONSTRAINT fk_order_product_orders
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE
);

CREATE INDEX idx_order_product_product   ON order_product (product_id);
CREATE INDEX idx_order_product_assistant ON order_product (assistant_stone_id);

-- 재고 (audit: BaseTimeEntity, soft-delete via stock_deleted)
-- ProductSnapshot @Embeddable 컬럼이 그대로 인라인되어 있다.
-- denorm vs freeze 구분은 order_product 와 동일한 의미 체계.
CREATE TABLE stock (
    stock_id                       BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code                     BIGINT,                                            -- TSID
    flow_code                      BIGINT,
    -- 2026-05 P4: store_name/factory_name 제거. 이름은 storeFinder/factoryFinder 로 조회.
    store_id                       BIGINT,                                            -- account.store FK
    store_harry                    NUMERIC(10, 2),                                    -- freeze (당시 수수료)
    store_grade                    VARCHAR(255),                                      -- freeze (당시 등급)
    factory_id                     BIGINT,                                            -- account.factory FK
    factory_harry                  NUMERIC(10, 2),                                    -- freeze (당시 수수료)
    stock_note                     TEXT,
    stock_main_stone_note          TEXT,
    stock_assistance_stone_note    TEXT,
    stone_main_labor_cost          INTEGER,                                           -- freeze (등급별)
    stone_assistance_labor_cost    INTEGER,                                           -- freeze
    stone_add_labor_cost           INTEGER,
    total_stone_purchase_cost      INTEGER,
    total_stone_labor_cost         INTEGER,
    stock_deleted                  BOOLEAN         NOT NULL DEFAULT FALSE,
    stock_checked                  BOOLEAN         DEFAULT FALSE,
    stock_checked_at               TIMESTAMP,
    -- ProductSnapshot @Embedded 인라인 컬럼군 시작 ----------------------------------
    product_id                     BIGINT,                                            -- product FK
    product_name                   VARCHAR(255),                                      -- denorm
    product_factory_name           VARCHAR(255),                                      -- denorm
    product_size                   VARCHAR(255),
    is_product_weight_sale         BOOLEAN         DEFAULT FALSE,
    product_labor_cost             INTEGER,                                           -- freeze
    product_add_labor_cost         INTEGER,                                           -- freeze
    product_purchase_cost          INTEGER,                                           -- freeze
    material_id                    BIGINT,                                            -- denorm
    material_name                  VARCHAR(255),                                      -- denorm
    color_id                       BIGINT,                                            -- denorm
    color_name                     VARCHAR(255),                                      -- denorm
    classification_id              BIGINT,                                            -- denorm
    classification_name            VARCHAR(255),                                      -- denorm
    set_type_id                    BIGINT,                                            -- denorm
    set_type_name                  VARCHAR(255),                                      -- denorm
    assistant_stone                BOOLEAN         NOT NULL DEFAULT FALSE,
    assistant_stone_id             BIGINT,
    assistant_stone_name           VARCHAR(255),                                      -- denorm
    assistant_stone_create_at      TIMESTAMP,
    gold_weight                    NUMERIC(10, 3),
    stone_weight                   NUMERIC(10, 3),
    -- ProductSnapshot 인라인 컬럼군 끝 -----------------------------------------------
    order_id                       BIGINT          UNIQUE,                            -- @OneToOne(Orders)
    order_status                   VARCHAR(30)     NOT NULL,
    create_date                    TIMESTAMP,
    last_modified_date             TIMESTAMP,
    CONSTRAINT fk_stock_orders
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
);

CREATE INDEX idx_stock_flow_code        ON stock (flow_code);
CREATE INDEX idx_stock_store            ON stock (store_id);
CREATE INDEX idx_stock_factory          ON stock (factory_id);
CREATE INDEX idx_stock_status           ON stock (order_status);
CREATE INDEX idx_stock_product          ON stock (product_id);

-- 주문 스톤 (Orders 또는 Stock 에 연결, audit 미상속)
CREATE TABLE order_stone (
    order_stone_id        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_stone_id       BIGINT,                                            -- product.stone FK
    origin_stone_name     VARCHAR(255),                                      -- denorm
    origin_stone_weight   NUMERIC(10, 3),
    stone_purchase_cost   INTEGER,                                           -- freeze 매입가
    stone_labor_cost      INTEGER,                                           -- freeze 판매공임
    stone_add_labor_cost  INTEGER,                                           -- freeze 추가공임
    stone_quantity        INTEGER,
    is_main_stone         BOOLEAN,
    is_include_stone      BOOLEAN,
    order_id              BIGINT,
    stock_id              BIGINT,
    CONSTRAINT fk_order_stone_orders
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_stone_stock
        FOREIGN KEY (stock_id) REFERENCES stock (stock_id) ON DELETE CASCADE
);

CREATE INDEX idx_order_stone_order   ON order_stone (order_id);
CREATE INDEX idx_order_stone_stock   ON order_stone (stock_id);
CREATE INDEX idx_order_stone_origin  ON order_stone (origin_stone_id);

-- 상태 이력 (FK 없이 flow_code 로 추적. audit 미상속)
CREATE TABLE status_history (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_code    BIGINT       NOT NULL,
    source_type  VARCHAR(30),                                       -- enum SourceType
    phase        VARCHAR(30),                                       -- enum BusinessPhase
    kind         VARCHAR(30),                                       -- enum Kind
    from_value   VARCHAR(255),
    to_value     VARCHAR(255),
    content      TEXT,
    created_at   TIMESTAMP,                          -- 엔티티상 createAt
    user_name    VARCHAR(255)
);

CREATE INDEX idx_status_history_flow_code   ON status_history (flow_code);
CREATE INDEX idx_status_history_phase       ON status_history (phase);
CREATE INDEX idx_status_history_kind        ON status_history (kind);

-- 판매 (audit: BaseEntity)
CREATE TABLE sale (
    sale_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_code            BIGINT          NOT NULL,                          -- TSID
    sale_status          VARCHAR(30),                                       -- enum SaleStatus
    account_id           BIGINT          NOT NULL,                          -- account.store FK 의미
    account_name         VARCHAR(255)    NOT NULL,                          -- denorm (account 분리 잔재)
    account_harry        NUMERIC(10, 2),                                    -- freeze (판매시점 환율)
    account_grade        VARCHAR(255),                                      -- denorm (등급)
    account_gold_price   INTEGER,                                           -- freeze (판매시점 금시세)
    display_code         VARCHAR(10),                                       -- 화면 표시용 단축 코드
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP,
    created_by           VARCHAR(255),
    last_modified_by     VARCHAR(255),
    CONSTRAINT uk_sale_code UNIQUE (sale_code)
);

CREATE INDEX idx_sale_account       ON sale (account_id);
CREATE INDEX idx_sale_status        ON sale (sale_status);
CREATE INDEX idx_sale_create_date   ON sale (create_date);

-- 판매 항목 (audit: BaseEntity, stock 1:1)
CREATE TABLE sale_item (
    sale_item_id         BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id              BIGINT,
    stock_id             BIGINT,
    flow_code            BIGINT          NOT NULL,
    item_status          VARCHAR(30)     NOT NULL DEFAULT 'SALE',
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP,
    created_by           VARCHAR(255),
    last_modified_by     VARCHAR(255),
    CONSTRAINT uk_sale_item_stock UNIQUE (stock_id),
    CONSTRAINT fk_sale_item_sale
        FOREIGN KEY (sale_id) REFERENCES sale (sale_id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_item_stock
        FOREIGN KEY (stock_id) REFERENCES stock (stock_id)
);

CREATE INDEX idx_sale_item_sale       ON sale_item (sale_id);
CREATE INDEX idx_sale_item_flow_code  ON sale_item (flow_code);

-- 판매 결제 (audit: BaseEntity)
CREATE TABLE sale_payment (
    sale_payment_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id              BIGINT          NOT NULL,
    flow_code            BIGINT          NOT NULL,
    sale_status          VARCHAR(30),                                       -- 결제 시점 판매 상태
    cash_amount          INTEGER         DEFAULT 0,
    gold_material        VARCHAR(255),
    pure_gold_weight     NUMERIC(18, 3)  DEFAULT 0,
    gold_weight          NUMERIC(18, 3)  DEFAULT 0,
    payment_note         TEXT,
    event_id             VARCHAR(100)    NOT NULL,
    payment_deleted      BOOLEAN         NOT NULL DEFAULT FALSE,
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP,
    created_by           VARCHAR(255),
    last_modified_by     VARCHAR(255),
    CONSTRAINT uk_payment_idevt UNIQUE (event_id),
    CONSTRAINT fk_sale_payment_sale
        FOREIGN KEY (sale_id) REFERENCES sale (sale_id) ON DELETE CASCADE
);

CREATE INDEX ix_payment_sale ON sale_payment (sale_id, create_date);

-- 2026-05 P3: Outbox 자체 구현 제거. order/internal/outbox/ 패키지가 삭제되었으므로
--             out_box_event 테이블도 DDL 에서 제외. 외부 비동기 전달이 다시 필요해지면
--             Spring Modulith 의 event_publication 테이블을 채택할 것.

-- ====================================================================
-- 5. user 모듈 (tenant_id 컬럼 보유 - 글로벌/공용 데이터)
-- ====================================================================

-- 사용자 (audit: BaseTimeEntity, soft-delete via deleted)
CREATE TABLE users (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              VARCHAR(10)     NOT NULL,
    password             VARCHAR(100)    NOT NULL,
    nickname             VARCHAR(10)     NOT NULL,
    tenant_id            VARCHAR(10)     NOT NULL,
    role                 VARCHAR(10)     NOT NULL,
    store_id             BIGINT,
    deleted              BOOLEAN         NOT NULL DEFAULT FALSE,
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP
);

CREATE INDEX idx_users_tenant       ON users (tenant_id);
CREATE INDEX idx_users_user_id      ON users (user_id);
CREATE INDEX idx_users_store        ON users (store_id);

-- SENS 발송 설정 (audit: BaseTimeEntity)
CREATE TABLE sens_config (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            VARCHAR(10)     NOT NULL UNIQUE,
    access_key           VARCHAR(255)    NOT NULL,
    secret_key           VARCHAR(255)    NOT NULL,
    service_id           VARCHAR(255)    NOT NULL,
    sender_phone         VARCHAR(15)     NOT NULL,
    enabled              BOOLEAN         NOT NULL DEFAULT TRUE,
    create_date          TIMESTAMP,
    last_modified_date   TIMESTAMP
);

-- 메시지 발송 이력 (audit 미상속, created_at 자체 컬럼 보유)
CREATE TABLE message_history (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           VARCHAR(10)     NOT NULL,
    receiver_phone      VARCHAR(15)     NOT NULL,
    receiver_name       VARCHAR(50),
    content             TEXT            NOT NULL,
    status              VARCHAR(20)     NOT NULL,
    error_message       VARCHAR(500),
    naver_request_id    VARCHAR(100),
    sent_by             VARCHAR(50)     NOT NULL,
    created_at          TIMESTAMP
);

CREATE INDEX idx_message_history_tenant      ON message_history (tenant_id);
CREATE INDEX idx_message_history_created_at  ON message_history (created_at);

-- ====================================================================
-- 6. 시드 데이터: 기본 우선순위 (Priority)
--    OrderService.getDefaultPriority() 가 '일반' 우선순위를 orElseThrow 로
--    필수 조회하므로 미리 시드 1건을 넣어둔다 (기본 출고 등급).
-- ====================================================================

INSERT INTO priority (priority_name, priority_date) VALUES ('일반', 0);
INSERT INTO priority (priority_name, priority_date) VALUES ('급', 1);
INSERT INTO priority (priority_name, priority_date) VALUES ('초급', 2);

-- ====================================================================
-- End of V1
-- ====================================================================
