-- ============================================================================
-- V7 — balance_history 신설 (미수 잔액 변경 불변 이력)
-- ----------------------------------------------------------------------------
-- 배경:
--   잔액(factory/store.current_*_balance) 변경의 before/after 스냅샷이 sale_log 에
--   비동기 배치로만 쌓여 비원자·누락 위험이 있었음(마이그레이션 미적재 → null 버그).
--   모든 잔액 변경을 applyDelta 단일 경로에서 같은 트랜잭션으로 본 테이블에 기록한다.
--   (BALANCE_HISTORY_PLAN.md 의 옵션 B. sale_log 는 단계적으로 본 테이블로 통합/폐기)
--
-- 원칙:
--   - append-only: UPDATE/DELETE 금지. 정정은 역분개(REVERSAL) 행 추가로.
--   - event_id UNIQUE = 멱등키 (transaction_history 와 동일 관례, OPENING-* 백필 키 포함)
--
-- 멱등성: IF NOT EXISTS 가드.
-- ============================================================================

CREATE TABLE IF NOT EXISTS balance_history (
    balance_history_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type             VARCHAR(20)     NOT NULL,                 -- STORE / FACTORY
    store_id               BIGINT,
    factory_id             BIGINT,
    before_gold_balance    NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    after_gold_balance     NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    before_money_balance   BIGINT          NOT NULL DEFAULT 0,
    after_money_balance    BIGINT          NOT NULL DEFAULT 0,
    delta_gold             NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    delta_money            BIGINT          NOT NULL DEFAULT 0,
    reason                 VARCHAR(30)     NOT NULL,                 -- SALE/PAYMENT/RETURN/... + OPENING/REVERSAL
    event_id               VARCHAR(100)    NOT NULL UNIQUE,          -- 멱등키
    account_sale_code      BIGINT,                                   -- 판매 주문장 참조 (있을 때)
    note                   VARCHAR(255),
    create_date                TIMESTAMP,
    last_modified_date         TIMESTAMP,
    created_by                 VARCHAR(255),
    last_modified_by           VARCHAR(255),
    CONSTRAINT fk_balance_history_store
        FOREIGN KEY (store_id) REFERENCES store (store_id),
    CONSTRAINT fk_balance_history_factory
        FOREIGN KEY (factory_id) REFERENCES factory (factory_id)
);

CREATE INDEX IF NOT EXISTS idx_balance_history_factory ON balance_history (factory_id, create_date);
CREATE INDEX IF NOT EXISTS idx_balance_history_store   ON balance_history (store_id, create_date);
CREATE INDEX IF NOT EXISTS idx_balance_history_owner   ON balance_history (owner_type, create_date);
